name: analogcoderpro
channels:
  - defaults
dependencies:
  - python=3.13
  - numpy
  - scipy
  - pandas
  - matplotlib
  - cffi
  - pip
  - pip:
      - PySpice==1.5
      - openai>=2.0,<3
      - schemdraw==0.23
